#include "http_server.h"
#include "esp_http_server.h"
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
static httpd_handle_t s_sv=NULL; static test_cb_t s_test_cb=NULL; static set_key_cb_t s_key_cb=NULL; static reset_cb_t s_reset_cb=NULL; static status_cb_t s_status_cb=NULL; static rules_list_cb_t s_rules_list=NULL; static rules_add_cb_t s_rules_add=NULL; static rules_del_cb_t s_rules_del=NULL; static rules_fire_cb_t s_rules_fire=NULL;
void http_server_push_event(const char *event,const char *data){(void)event;(void)data;}
static const char *HTML="<!DOCTYPE html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>ESP32 Bridge</title><style>body{font-family:system-ui,sans-serif;background:#f7f6f2;color:#28251d;max-width:1000px;margin:0 auto;padding:24px}header{background:#01696f;color:#fff;padding:16px;border-radius:10px}.card{background:#fff;padding:16px;margin:16px 0;border-radius:10px;box-shadow:0 1px 5px rgba(0,0,0,.08)}button{background:#01696f;color:#fff;border:none;padding:10px 14px;border-radius:6px;margin-right:8px}</style></head><body><header><h1>ESP32 TUYA+SATEL Bridge</h1></header><div class='card'><h3>Status systemu</h3><pre id='out'>Ladowanie...</pre><button onclick='load()'>Odswiez</button></div><script>async function load(){let r=await fetch('/api/status');let t=await r.text();document.getElementById('out').textContent=t;}load();</script></body></html>";
static esp_err_t root_handler(httpd_req_t *r){httpd_resp_set_type(r,"text/html"); return httpd_resp_send(r,HTML,HTTPD_RESP_USE_STRLEN);} 
static esp_err_t status_handler(httpd_req_t *r){httpd_resp_set_type(r,"application/json"); if(s_status_cb){char *j=s_status_cb(); if(j){httpd_resp_sendstr(r,j); free(j); return ESP_OK;}} return httpd_resp_sendstr(r,"{\"state\":\"boot\"}");}
static esp_err_t rules_get_handler(httpd_req_t *r){httpd_resp_set_type(r,"application/json"); if(s_rules_list){char *j=s_rules_list(); if(j){httpd_resp_sendstr(r,j); free(j); return ESP_OK;}} return httpd_resp_sendstr(r,"{\"rules\":[]}");}
static esp_err_t rules_post_handler(httpd_req_t *r){char buf[512]={}; int n=httpd_req_recv(r,buf,sizeof(buf)-1); if(n<0)n=0; buf[n]='\0'; httpd_resp_set_type(r,"application/json"); if(s_rules_add&&s_rules_add(buf)==ESP_OK) return httpd_resp_sendstr(r,"{\"ok\":true}"); return httpd_resp_sendstr(r,"{\"ok\":false}");}
static esp_err_t test_handler(httpd_req_t *r){const char *t=strstr(r->uri,"tuya")?"tuya":"satel"; httpd_resp_set_type(r,"application/json"); if(s_test_cb&&s_test_cb(t)==ESP_OK) return httpd_resp_sendstr(r,"{\"ok\":true}"); return httpd_resp_sendstr(r,"{\"ok\":false}");}
static esp_err_t key_handler(httpd_req_t *r){char buf[128]={}; int n=httpd_req_recv(r,buf,sizeof(buf)-1); if(n<0)n=0; buf[n]='\0'; httpd_resp_set_type(r,"application/json"); if(s_key_cb&&s_key_cb(buf)==ESP_OK) return httpd_resp_sendstr(r,"{\"ok\":true}"); return httpd_resp_sendstr(r,"{\"ok\":false}");}
static esp_err_t reset_handler(httpd_req_t *r){httpd_resp_set_type(r,"application/json"); httpd_resp_sendstr(r,"{\"ok\":true}"); if(s_reset_cb)s_reset_cb(); return ESP_OK;}
esp_err_t http_server_start(const char *user,const char *pass){(void)user;(void)pass; httpd_config_t cfg=HTTPD_DEFAULT_CONFIG(); cfg.max_uri_handlers=12; cfg.stack_size=8192; ESP_ERROR_CHECK(httpd_start(&s_sv,&cfg)); httpd_uri_t a={"/",HTTP_GET,root_handler,NULL}; httpd_uri_t b={"/api/status",HTTP_GET,status_handler,NULL}; httpd_uri_t c={"/api/rules",HTTP_GET,rules_get_handler,NULL}; httpd_uri_t d={"/api/rules",HTTP_POST,rules_post_handler,NULL}; httpd_uri_t e={"/api/test/tuya",HTTP_POST,test_handler,NULL}; httpd_uri_t f={"/api/test/satel",HTTP_POST,test_handler,NULL}; httpd_uri_t g={"/api/key",HTTP_POST,key_handler,NULL}; httpd_uri_t h={"/api/reset",HTTP_POST,reset_handler,NULL}; httpd_register_uri_handler(s_sv,&a); httpd_register_uri_handler(s_sv,&b); httpd_register_uri_handler(s_sv,&c); httpd_register_uri_handler(s_sv,&d); httpd_register_uri_handler(s_sv,&e); httpd_register_uri_handler(s_sv,&f); httpd_register_uri_handler(s_sv,&g); httpd_register_uri_handler(s_sv,&h); return ESP_OK;}
void http_server_set_test_cb(test_cb_t cb){s_test_cb=cb;} void http_server_set_key_cb(set_key_cb_t cb){s_key_cb=cb;} void http_server_set_reset_cb(reset_cb_t cb){s_reset_cb=cb;} void http_server_set_status_cb(status_cb_t cb){s_status_cb=cb;} void http_server_set_rules_api_cb(rules_list_cb_t l, rules_add_cb_t a, rules_del_cb_t d, rules_fire_cb_t f){s_rules_list=l; s_rules_add=a; s_rules_del=d; s_rules_fire=f;}
