#include "tuya_http.h"
#include "esp_http_client.h"
#include "esp_crt_bundle.h"
#include "mbedtls/sha256.h"
#include "mbedtls/md.h"
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
static char s_rbuf[4096]; static int s_rlen=0;
static esp_err_t evt_handler(esp_http_client_event_t *e){ if(e->event_id==HTTP_EVENT_ON_DATA&&e->data_len>0&&s_rlen+e->data_len<(int)sizeof(s_rbuf)-1){ memcpy(s_rbuf+s_rlen,e->data,e->data_len); s_rlen+=e->data_len; } return ESP_OK; }
static void hmac_sha256_hex(const char *key,const char *msg,char *out_hex){ uint8_t mac[32]; mbedtls_md_context_t ctx; mbedtls_md_init(&ctx); const mbedtls_md_info_t *md=mbedtls_md_info_from_type(MBEDTLS_MD_SHA256); mbedtls_md_setup(&ctx,md,1); mbedtls_md_hmac_starts(&ctx,(const unsigned char*)key,strlen(key)); mbedtls_md_hmac_update(&ctx,(const unsigned char*)msg,strlen(msg)); mbedtls_md_hmac_finish(&ctx,mac); mbedtls_md_free(&ctx); for(int i=0;i<32;i++) sprintf(out_hex+i*2,"%02X",(unsigned)mac[i]); out_hex[64]='\0'; }
static void sha256_hex(const char *s,char *out){ unsigned char h[32]; mbedtls_sha256((const unsigned char*)s,strlen(s),h,0); for(int i=0;i<32;i++) sprintf(out+i*2,"%02x",(unsigned)h[i]); out[64]='\0'; }
static void build_sign(const char *cid,const char *secret,const char *token,const char *method,const char *path,const char *body,char *sign_out,char *ts_out,char *nonce_out){ long long ts=(long long)time(NULL)*1000; snprintf(ts_out,16,"%lld",ts); snprintf(nonce_out,32,"%08lx",(unsigned long)(ts&0xFFFFFFFF)); char body_hash[65]; sha256_hex(body&&*body?body:"",body_hash); char str_to_sign[512]; snprintf(str_to_sign,sizeof(str_to_sign),"%s\n%s\n\n%s",method,body_hash,path); char to_sign[640]; snprintf(to_sign,sizeof(to_sign),"%s%s%s%s%s",cid,token?token:"",ts_out,nonce_out,str_to_sign); hmac_sha256_hex(secret,to_sign,sign_out); }
static esp_err_t do_req(const char *host,const char *path,const char *method,const char *token,const char *cid,const char *secret,const char *body,tuya_resp_t *out){ char url[256]; snprintf(url,sizeof(url),"https://%s%s",host,path); char sign[65]={},ts[16]={},nonce[32]={}; build_sign(cid,secret,token,method,path,body,sign,ts,nonce); esp_http_client_config_t cfg={}; cfg.url=url; cfg.event_handler=evt_handler; cfg.transport_type=HTTP_TRANSPORT_OVER_SSL; cfg.crt_bundle_attach=esp_crt_bundle_attach; esp_http_client_handle_t h=esp_http_client_init(&cfg); esp_http_client_set_header(h,"client_id",cid); esp_http_client_set_header(h,"sign",sign); esp_http_client_set_header(h,"t",ts); esp_http_client_set_header(h,"nonce",nonce); esp_http_client_set_header(h,"sign_method","HMAC-SHA256"); esp_http_client_set_header(h,"Content-Type","application/json"); if(token&&*token) esp_http_client_set_header(h,"access_token",token); esp_http_client_set_method(h,strcmp(method,"POST")==0?HTTP_METHOD_POST:HTTP_METHOD_GET); if(body&&*body) esp_http_client_set_post_field(h,body,strlen(body)); s_rlen=0; memset(s_rbuf,0,sizeof(s_rbuf)); esp_err_t e=esp_http_client_perform(h); out->status=esp_http_client_get_status_code(h); out->body=strndup(s_rbuf,s_rlen); esp_http_client_cleanup(h); return e; }
esp_err_t tuya_http_get(const char *host,const char *path,const char *token,const char *client_id,const char *secret,tuya_resp_t *out){ return do_req(host,path,"GET",token,client_id,secret,NULL,out);} 
esp_err_t tuya_http_post(const char *host,const char *path,const char *token,const char *client_id,const char *secret,const char *body,tuya_resp_t *out){ return do_req(host,path,"POST",token,client_id,secret,body,out);} void tuya_resp_free(tuya_resp_t *r){free(r->body); r->body=NULL;}
